
LANG_JA = {
    "init":"ようこそ Anison Playlist Generator へ.", 
    "path_to_data":"アニソンデータ: ",
    "path_to_library":"音楽ライブラリ: ",
    "path_to_playlist":"出力先 (.m3u)  : ",
    "advanced_settings":"           詳細設定",
    "select":"選択",
    "tips_data":"アニソンデータベースが保存されているフォルダを選択してください.",
    "tips_library":"音楽ライブラリを選択してください.",
    "tips_playlist":"出力するプレイリストを選択してください.",
    "tips_cat_anime":"プレイリストにアニメの曲を含めます.",
    "tips_cat_game":"プレイリストにゲームの曲を含めます.",
    "tips_cat_sf":"プレイリストに特撮の曲を含めます.",
    "tips_keyword":"チェックを入れると特定の作品のプレイリストを作成します.",
    "tips_gen_only":"チェックを入れるとアニソンデータと音楽ライブラリの取得をスキップします.\n(初回実行, もしくはデータベースを更新するときにチェックを入れてください.)",
    "tips_dup":"チェックを入れると同一歌手名の同名の曲を含んだプレイリストを作成します.",
    "tips_rate_artist":"100に設定すると歌手名が完全に一致した場合にプレイリストに加えます.\n例えば, 歌手名(cv. 声優名)といった曲を追加したい場合は値を小さくすることでプレイリストに追加されるようになります.",
    "tips_rate_title":"100に設定すると曲名が完全に一致した場合にプレイリストに加えます.\n例えば, 曲名(Live ver.)といった曲を追加したい場合は値を小さくすることでプレイリストに追加されるようになります.",
    "tips_run":"プレイリストを作成します.",
    "tips_stop":"プレイリスト生成を中止します.",
    "tips_line_keyword":"何も入力されていない場合はすべてのアニメが対象のプレイリストを作成します.",
    "tips_database":"データベースを更新します.",
    "category":"カテゴリ: ",
    "anime":"アニメ",
    "game":"ゲーム",
    "sf":"特撮",
    "anime_title":"作品名 : ",
    "gen_playlist_only":"プレイリスト生成のみ実行",
    "allow_dup":"同じ曲名の重複を許可",
    "rate_title":"曲名の類似度 :",
    "rate_artist":"歌手名の類似度 :",
    "run":"実行",
    "stop":"中止",
    "db_update":"DB更新",
    "enable":"を有効にしました.",
    "disable":"を無効にしました.",
    "changed":"を変更しました.",
    "pressed":"が押されました.",
    "warn_gen_playlist":"プレイリスト生成のみ実行を無効にしてから実行してください",
    "warn_stop":"プレイリスト作成を中断しました.",
    "warn_ext":"拡張子は.m3uにしてください.",
    "make_anison":"アニソンデータベースを取得しています.",
    "make_library":"ライブラリを取得しています.",
    "make_playlist":"プレイリストを生成しています.",
    "fin_making_playlist":"プレイリストの生成が終了しました.",
    "fin_updating_database":"データベースの更新が終了しました．",
    "warn_overwrite":"警告",
    "message_overwrite":"同名の.m3uファイルが存在します.\n 上書きしますか?"
}

LANG_ENG = {
    "init":"Welcome to Anison Playlist Generator.", 
    "path_to_data":"Anime Songs: ",
    "path_to_library":"Music Library: ",
    "path_to_playlist":"Output (.m3u)  : ",
    "advanced_settings":" Advanced Settings ",
    "select":"Select",
    "tips_data":"アニソンデータベースが保存されているフォルダを選択してください.",
    "tips_library":"音楽ライブラリを選択してください.",
    "tips_playlist":"出力するプレイリストを選択してください.",
    "tips_cat_anime":"プレイリストにアニメの曲を含めます.",
    "tips_cat_game":"プレイリストにゲームの曲を含めます.",
    "tips_cat_sf":"プレイリストに特撮の曲を含めます.",
    "tips_keyword":"チェックを入れると一つの作品限定のプレイリストを作成します.",
    "tips_gen_only":"チェックを入れるとアニソンデータと音楽ライブラリの取得をスキップします.\n(初回実行, もしくはデータベースを更新するときにチェックを入れてください.)",
    "tips_dup":"チェックを入れると同一歌手名の同名の曲を含んだプレイリストを作成します.",
    "tips_rate_artist":"100に設定すると歌手名が完全に一致した場合にプレイリストに加えます.\n例えば, 歌手名(cv. 声優名)といった曲を追加したい場合は値を小さくすることでプレイリストに追加されるようになります.",
    "tips_rate_title":"100に設定すると曲名が完全に一致した場合にプレイリストに加えます.\n例えば, 曲名(Live ver.)といった曲を追加したい場合は値を小さくすることでプレイリストに追加されるようになります.",
    "tips_run":"プレイリストを作成します.",
    "tips_stop":"プレイリスト生成を中止します.",
    "tips_line_keyword":"何も入力されていない場合はすべてのアニメが対象のプレイリストを作成します.",
    "category":"Category: ",
    "anime":"Anime",
    "game":"Game",
    "sf":"SF",
    "anime_title":"作品名 : ",
    "gen_playlist_only":"Run only playlist generation",
    "allow_dup":"Allow duplication",
    "rate_title":"Ratio of title :",
    "rate_artist":"Ratio of artist :",
    "run":"Run",
    "stop":"Stop",
    "enable":"was enabled.",
    "disable":"was disabled.",
    "changed":"was changed.",
    "pressed":"was pressed.",
    "warn_gen_playlist":"You must run without \"Run only playlist generation\"",
    "warn_stop":"Playlist generation was interrupted.",
    "warn_ext":"The extension should be .m3u.",
    "make_anison":"Acquiring the anison Database.",
    "make_library":"Acquiring the music library.",
    "make_playlist":"Generating the playlist.",
    "make_fin":"Playlist generation finished.",
    "warn_overwrite":"Warning",
    "message_overwrite":"A Playlist file exists. \n Overwrite?"
}